### ISSUE TITLE
Function normalize_Insta_user_url too loose

### ISSUE THREAD

**Issue by fcatt** [wltb/ff_instagram#2]
Hi, thank you for the fast update :+1: 
In the past I had to change the regex in init.php l. 76 because it prevented me to subscribe to the Instagram Engineering Blog (engineering.instagram.com hosted on Medium). After the last update this particular feed showed me the updates of the instagram.com/feed user, not what I wanted!  :smiley: 
My own line 76 is now: `if(! preg_match('/^(www\.)?instagram\.com$/i', $host)) return;`

**Comment by wltb** [comment]
Ah. I guess this sometimes happens while hijacking URLs 😉 
I'll take a look; BTW, do you know other instagram RSS feeds? I think I can recall that one could subscribe to tags.

**Comment by fcatt** [comment]
An example of tag feed is https://www.instagram.com/explore/tags/stephenhawking/
and for the location feed, something like
https://www.instagram.com/explore/locations/463061954/lyon-place-bellecour/
You can browse locations with your browser from https://www.instagram.com/explore/locations/ to get the location numeric ID (the last term of the URL, /lyon-place-bellecour/ in my case, is optional).
