### ISSUE TITLE
feed_has_icon() function is undefined

### ISSUE THREAD

**Issue by fcatt** [wltb/ff_instagram#3]
Using last TT-RSS code (master branch from GIT), had to comment the whole **function feed_has_icon()** test block (init.php lines 39 to 46) to prevent the following error:
```php
==> ttrssd_err.log <==
PHP Fatal error:  Uncaught Error: Call to undefined function feed_has_icon() in /usr/local/www/tt-rss/plugins/ff_instagram/init.php:39
Stack trace:
#0 /usr/local/www/tt-rss/plugins/ff_instagram/init.php(402): ff_Instagram::check_feed_icon('https://instagr...', 945)
#1 /usr/local/www/tt-rss/classes/rssutils.php(494): ff_Instagram->hook_feed_fetched('{"logging_page_...', 'https://instagr...', 2, 945)
#2 /usr/local/www/tt-rss/classes/rssutils.php(190): RSSUtils::update_rss_feed(945, true, false)
#3 /usr/local/www/tt-rss/update.php(199): RSSUtils::update_daemon_common(50)
#4 {main}
  thrown in /usr/local/www/tt-rss/plugins/ff_instagram/init.php on line 39
```

**Comment by wltb** [comment]
Ah, yes. I'm not using the latest code ATM. Would you try if replacing `feed_has_icon` with `Feeds::feedHasIcon` works? When it does, you could also try to replace `$icon_file = ICONS_DIR . "/$feed_id.ico";` with `$icon_file = Feeds::getIconFile($feed_id);`.

BTW, does the DB stuff in `hook_feed_fetched` work?

**Comment by fcatt** [comment]
Replacing `feed_has_icon` with `Feeds::feedHasIcon` works.
Replacing `$icon_file = ICONS_DIR . "/$feed_id.ico";` with `$icon_file = Feeds::getIconFile($feed_id);` works too.

Added two new Instagram feeds with success, but maybe related with the `hook_feed_fetched` stuff: The **Site URL** field is not populated automatically in the **Edit field** panel, and this value is mandatory to save the changes (generally replacing the **[Unknown]** feed name and unticking **Include in e-mail digest** in my case).

**Comment by wltb** [comment]
I think that's a limitation of the Tiny Tiny RSS core, and that another plugin hook was added to address this problem. I'll take a look at this this week, and maybe add a separate git branch. In the meantime, you can copy/paste the feed URL to the site URL and set some title.

**Comment by fcatt** [comment]
Yes that's what I am doing (I don't subscribe very often to new Instagram feeds so it don't bother me). Thank you again for your good work @wltb :slightly_smiling_face:

**Comment by wltb** [comment]
Should be fixed now.
